version: '3.8'
#Este archivo le dice a Docker: "Levantame un servidor MinIO y dame una carpeta para guardar los datos".

x-shared-config: &backend-config
    build: .
    container_name: fast_api_medical
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    depends_on:
      - minio
    networks:
      - medical_network

services:
  # CAMBIO AQUÍ: De 'minio_local' a 'minio'
  minio:
    image: minio/minio:latest
    container_name: minio # <--- SIN GUION BAJO
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
    networks:
      - medical_network

  backend_cpu:
    <<: *backend-config
    profiles:
      - cpu

  backend_nvidia:
    <<: *backend-config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles:
      - gpu-nvidia


networks:
  medical_network:
    driver: bridge
